(() => {
  'use strict';
  const BUILD = '26.0.0-github-main-ui';
  window.PROXYHARVEST_UI_PATCH = BUILD;
  const $ = (s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const state=()=>window.PH_STATE||{configs:[],splitnetConfigs:[]};
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  const clean=v=>String(v??'').replace(/[<>]/g,'').slice(0,300);
  const toast=(m,t='info')=>{if(typeof window.toast==='function')return window.toast(m,t);const e=document.createElement('div');e.className=`phv26-toast ${t}`;e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),3200)};
  const verified=c=>c?.probe?.tunnelVerified===true||c?.probe?.protocolVerified===true||(typeof window.verificationPass==='function'&&window.verificationPass(c)===true);
  const reachable=c=>{const p=c?.probe||{};return p.browserReachable===true||p.workerReachable===true||p.bridgeReachable===true||c?.reachable===true};
  const failed=c=>c?.tested===true&&c?.live===false&&!reachable(c)&&!verified(c);
  const latency=c=>{const v=Number(c?.probe?.latencyMs??c?.latency);return Number.isFinite(v)&&v>=0&&v<9999?v:Infinity};
  const score=c=>num(c?.score);
  function uri(c){try{if(typeof window.getExportUri==='function')return window.getExportUri(c,{allowSensitive:false})||''}catch{}const r=String(c?.raw||'');if(!r||/REDACTED|\*\*\*/i.test(r)||/privatekey=|private_key=/i.test(r)||r.toLowerCase().startsWith('wireguard://'))return'';return r}
  function rank(a){return a.slice().sort((x,y)=>{const xv=verified(x)?2:reachable(x)?1:0,yv=verified(y)?2:reachable(y)?1:0;if(yv!==xv)return yv-xv;if(score(y)!==score(x))return score(y)-score(x);return latency(x)-latency(y)})}
  function counts(a=state().configs||[]){try{const c=window.PROXYHARVEST_V32?.counts?.(a);if(c)return{verified:num(c.verified),reachable:num(c.reachable),untested:num(c.untested),failed:num(c.failed)}}catch{}const o={verified:0,reachable:0,untested:0,failed:0};for(const c of a){if(verified(c))o.verified++;else if(failed(c))o.failed++;else if(reachable(c))o.reachable++;else o.untested++}return o}
  function bridge(){const i=$('#localBridgeUrl')?.value?.trim();let s='';try{s=localStorage.getItem('ph_real_ping_bridge')||''}catch{}return String(i||s).replace(/\/$/,'')}
  function dl(n,t,ty='text/plain;charset=utf-8'){const b=new Blob([t],{type:ty}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
  function b64(t){const bytes=new TextEncoder().encode(t);let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
  const PH_V26_MUTATION_STABILITY = '40.0.0';
  function setTextStable(el,value){if(!el)return false;const next=String(value??'');if(el.textContent===next)return false;el.textContent=next;return true}
  const PH_V41_IDLE_STABILITY = '41.0.0';
  const phV41HtmlCache=new WeakMap();
  function htmlStructurallyEqual(el,next){if(el.innerHTML===next)return true;const tpl=document.createElement('template');tpl.innerHTML=next;const current=el.childNodes,wanted=tpl.content.childNodes;if(current.length!==wanted.length)return false;for(let i=0;i<current.length;i++)if(!current[i].isEqualNode(wanted[i]))return false;return true}
  function setHtmlStable(el,value){if(!el)return false;const next=String(value??'');if(phV41HtmlCache.get(el)===next&&htmlStructurallyEqual(el,next))return false;if(htmlStructurallyEqual(el,next)){phV41HtmlCache.set(el,next);return false}el.innerHTML=next;phV41HtmlCache.set(el,next);return true}

  function ensureConfigs(){const tab=$('#tab-configs');if(!tab||$('#phv26ConfigNav',tab))return;const ribbon=$('.cfg-stats-ribbon',tab)||tab.firstElementChild;const nav=document.createElement('div');nav.id='phv26ConfigNav';nav.className='phv26-subnav';nav.innerHTML='<button class="active" data-phv26-config="library">Library</button><button data-phv26-config="verify">Verification</button><button data-phv26-config="export">Best Export</button><span class="phv26-subnav-note">REACHABLE is never promoted to VERIFIED.</span>';ribbon?.insertAdjacentElement('afterend',nav);
    const vp=document.createElement('section');vp.id='phv26VerifyPanel';vp.className='phv26-config-panel';vp.hidden=true;vp.innerHTML='<div class="phv26-panel-head"><div><b>Verification Center</b><span>Endpoint reachability, real protocol/tunnel verification, and failure state stay separate.</span></div><div class="phv26-inline-actions"><button class="phv26-btn" id="phv26ProbeBtn">Probe batch</button><button class="phv26-btn primary" id="phv26RealVerifyBtn">Real Verify</button><button class="phv26-btn danger" id="phv26StopVerifyBtn">Stop</button></div></div><div class="phv26-metrics" id="phv26VerifyMetrics"></div><div class="phv26-verify-grid"><div><label>Real Test Bridge</label><b id="phv26BridgeState">Checking…</b><small id="phv26BridgeDetail">Strict verification needs the local Real Test Bridge/Engine.</small></div><div><label>Worker / browser probe</label><b>Reachability only</b><small>Useful for endpoint screening; never counted as protocol/tunnel verified.</small></div><div><label>WireGuard</label><b>Handshake required</b><small>A Worker HTTP probe cannot verify a WireGuard tunnel.</small></div></div>';nav.insertAdjacentElement('afterend',vp);
    const ep=document.createElement('section');ep.id='phv26ExportPanel';ep.className='phv26-config-panel';ep.hidden=true;ep.innerHTML='<div class="phv26-panel-head"><div><b>Best Config Export</b><span>Ranked by verification state, score, then latency. Verified-only is the safe default.</span></div></div><div class="phv26-export-controls"><label>Bucket<select id="phv26ExportBucket"><option value="verified">Verified only</option><option value="reachable">Reachable candidates</option><option value="mixed">Verified + reachable</option></select></label><label>Min score<input id="phv26ExportScore" type="number" min="0" max="100" value="70"></label><label>Max rows<input id="phv26ExportLimit" type="number" min="1" max="5000" value="100"></label><label>Protocol<select id="phv26ExportProto"><option value="">All</option><option>vless</option><option>vmess</option><option>trojan</option><option>ss</option><option>wireguard</option><option>hy2</option><option>tuic</option></select></label><button class="phv26-btn" id="phv26RefreshExport">Refresh</button><button class="phv26-btn primary" id="phv26CopyExport">Copy</button><button class="phv26-btn" id="phv26DownloadExport">.txt</button><button class="phv26-btn" id="phv26DownloadB64">Base64</button></div><div class="phv26-export-note" id="phv26ExportNote"></div><div class="phv26-export-preview"><table><thead><tr><th>#</th><th>Protocol</th><th>Endpoint</th><th>State</th><th>Score</th><th>Latency</th><th>Source</th></tr></thead><tbody id="phv26ExportRows"></tbody></table></div>';vp.insertAdjacentElement('afterend',ep);
    nav.addEventListener('click',e=>{const b=e.target.closest('[data-phv26-config]');if(!b)return;const s=b.dataset.phv26Config;$$('button',nav).forEach(x=>x.classList.toggle('active',x===b));[$('.cfgs-hdr',tab),$('.cfgs-action-bar',tab),$('#cfgsTableWrap',tab)].filter(Boolean).forEach(x=>x.hidden=s!=='library');vp.hidden=s!=='verify';ep.hidden=s!=='export';if(s==='export')refreshExport();if(s==='verify')refreshVerify()});
    $('#phv26ProbeBtn')?.addEventListener('click',()=>typeof window.startRealTest==='function'?window.startRealTest({strictRealPing:false}).catch(e=>toast(clean(e?.message||e),'err')):toast('Real Test engine is not loaded.','err'));
    $('#phv26RealVerifyBtn')?.addEventListener('click',()=>{if(!bridge())return toast('Configure the Real Test Bridge first. Strict verification cannot fall back to browser/Worker probes.','warn');if(typeof window.startRealTest!=='function')return toast('Real Test engine is not loaded.','err');window.startRealTest({strictRealPing:true}).catch(e=>toast(clean(e?.message||e),'err'))});
    $('#phv26StopVerifyBtn')?.addEventListener('click',()=>window.stopRealTest?.());
    ['phv26ExportBucket','phv26ExportScore','phv26ExportLimit','phv26ExportProto'].forEach(id=>$('#'+id)?.addEventListener('input',refreshExport));$('#phv26RefreshExport')?.addEventListener('click',refreshExport);$('#phv26CopyExport')?.addEventListener('click',()=>doExport('copy'));$('#phv26DownloadExport')?.addEventListener('click',()=>doExport('txt'));$('#phv26DownloadB64')?.addEventListener('click',()=>doExport('b64'));refreshVerify();refreshExport()}
  function refreshVerify(){const r=$('#phv26VerifyMetrics');if(!r)return;const c=counts();const html=`<div class="good"><span>Verified</span><b>${c.verified.toLocaleString()}</b><small>Protocol/tunnel evidence</small></div><div class="info"><span>Reachable</span><b>${c.reachable.toLocaleString()}</b><small>Endpoint only</small></div><div><span>Untested</span><b>${c.untested.toLocaleString()}</b><small>No evidence yet</small></div><div class="bad"><span>Failed</span><b>${c.failed.toLocaleString()}</b><small>Latest probe failed</small></div>`;setHtmlStable(r,html);const b=bridge();setTextStable($('#phv26BridgeState'),b?'Configured':'Not configured');setTextStable($('#phv26BridgeDetail'),b||'Strict verification needs the local Real Test Bridge/Engine.')}
  function exportList(){const bucket=$('#phv26ExportBucket')?.value||'verified',min=num($('#phv26ExportScore')?.value||0),limit=Math.max(1,Math.min(5000,num($('#phv26ExportLimit')?.value||100))),proto=($('#phv26ExportProto')?.value||'').toLowerCase();let a=(state().configs||[]).filter(c=>score(c)>=min&&(!proto||String(c.type).toLowerCase()===proto));if(bucket==='verified')a=a.filter(verified);else if(bucket==='reachable')a=a.filter(c=>reachable(c)&&!verified(c));else a=a.filter(c=>verified(c)||reachable(c));return rank(a).filter(c=>uri(c)).slice(0,limit)}
  function refreshExport(){const body=$('#phv26ExportRows');if(!body)return;const a=exportList(),bucket=$('#phv26ExportBucket')?.value||'verified',n=$('#phv26ExportNote');const note=bucket==='verified'?`<b>${a.length}</b> verified configs ready. These have protocol/tunnel evidence.`:bucket==='reachable'?`<b>${a.length}</b> reachable-only candidates. <strong>They are not protocol/tunnel verified.</strong>`:`<b>${a.length}</b> ranked verified/reachable entries. State remains explicit.`;setHtmlStable(n,note);const rows=a.slice(0,40).map((c,i)=>`<tr><td>${i+1}</td><td>${clean(c.type||'—')}</td><td>${clean(c.host||'—')}:${num(c.port)||'—'}</td><td><span class="phv26-state ${verified(c)?'verified':'reachable'}">${verified(c)?'VERIFIED':'REACHABLE'}</span></td><td>${score(c)}</td><td>${latency(c)===Infinity?'—':Math.round(latency(c))+' ms'}</td><td>${clean(c.sourceName||c.source||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="phv26-empty">No configs match this export bucket.</td></tr>';setHtmlStable(body,rows)}
  async function doExport(mode){const a=exportList();if(!a.length)return toast('No configs match the selected bucket.','warn');const text=a.map(uri).filter(Boolean).join('\n'),bucket=$('#phv26ExportBucket')?.value||'verified',base=`proxyharvest-${bucket}-best-${a.length}-${new Date().toISOString().slice(0,10)}`;if(mode==='copy'){try{await navigator.clipboard.writeText(text);return toast(`${a.length} configs copied.`,'ok')}catch{return toast('Clipboard copy failed.','err')}}if(mode==='b64')dl(base+'.b64.txt',b64(text));else dl(base+'.txt',text);toast(`${a.length} configs exported from the ${bucket} bucket.`,bucket==='verified'?'ok':'warn')}

  function ensureSplit(){const tab=$('#tab-splitnet');if(!tab||$('#phv26SplitSummary',tab))return;const bar=$('.splitnet-bar',tab)||tab.firstElementChild,box=document.createElement('div');box.id='phv26SplitSummary';box.className='phv26-page-summary';box.innerHTML='<div><b>SplitNet candidates</b><span>Compact candidate view with provenance and truthful verification.</span></div><div class="phv26-summary-metrics" id="phv26SplitMetrics"></div>';bar?.insertAdjacentElement('beforebegin',box);refreshSplit()}
  function refreshSplit(){const r=$('#phv26SplitMetrics');if(!r)return;const a=state().splitnetConfigs||[],c=counts(a),wg=a.filter(x=>String(x.type).toLowerCase()==='wireguard').length;setHtmlStable(r,`<span><b>${a.length}</b>Total</span><span><b>${c.verified}</b>Verified</span><span><b>${c.reachable}</b>Reachable</span><span><b>${wg}</b>WG</span>`)}
  function ensureWG(){const tab=$('#tab-wireguard');if(!tab||$('#phv26WgSummary',tab))return;const anchor=$('.ph-wg-trust-banner',tab)||$('.wg-section-bar',tab),box=document.createElement('div');box.id='phv26WgSummary';box.className='phv26-wg-summary';anchor?.insertAdjacentElement('afterend',box);refreshWG()}
  function refreshWG(){const r=$('#phv26WgSummary');if(!r)return;const a=(state().configs||[]).filter(c=>String(c.type).toLowerCase()==='wireguard'),structure=a.filter(c=>c.host&&c.port&&c.publicKey).length,reach=a.filter(reachable).length,v=a.filter(verified).length;setHtmlStable(r,`<div><span>Structure valid</span><b>${structure}/${a.length}</b></div><div><span>Endpoint reachable</span><b>${reach}</b></div><div><span>Handshake / tunnel verified</span><b>${v}</b></div><small>Worker/browser reachability never becomes a WireGuard handshake.</small>`)}

  function candidates(c){const o=[],p=num(c?.port),h=String(c?.host||''),sec=String(c?.security||'').toLowerCase(),net=String(c?.net||c?.network||'').toLowerCase();if(!p||p>65535)o.push({id:'port-443',field:'port',value:443,rule_confidence:40,reason:'Conservative standard TLS port candidate; verification required.'});if(String(c?.type).toLowerCase()==='vless'&&sec==='reality'&&!c?.sni&&h&&!/^\d+(\.\d+){3}$/.test(h))o.push({id:'use-host-as-sni',field:'sni',value:h,rule_confidence:58,reason:'Hostname can be evaluated as an SNI candidate; verification required.'});if(net==='ws'&&!c?.path)o.push({id:'ws-root-path',field:'path',value:'/',rule_confidence:45,reason:'Conservative WebSocket path candidate; verification required.'});if(!o.length)o.push({id:'keep-original',field:'noop',value:null,rule_confidence:90,reason:'No bounded safe mutation found.'});return o}
  function advisorItem(c,index){const issues=[];if(!c?.host)issues.push({code:'missing_host',severity:'high',text:'Host missing'});if(!num(c?.port)||num(c?.port)>65535)issues.push({code:'invalid_port',severity:'high',text:'Port invalid'});if(String(c?.type).toLowerCase()==='vless'&&String(c?.security).toLowerCase()==='reality'&&!c?.sni)issues.push({code:'reality_sni',severity:'medium',text:'Reality config has no SNI'});if(latency(c)!==Infinity&&latency(c)>1500)issues.push({code:'high_latency',severity:'low',text:'Observed latency is high'});return{index,protocol:String(c?.type||'unknown'),endpoint:`${c?.host||'?'}:${num(c?.port)}`,security:String(c?.security||''),network:String(c?.net||c?.network||''),sni_present:Boolean(c?.sni),path_present:Boolean(c?.path),score:score(c),tested:c?.tested===true,live:c?.live===true?true:c?.live===false?false:null,latency_ms:latency(c)===Infinity?null:Math.round(latency(c)),verification:{method:String(c?.probe?.method||c?.testMethod||'none'),protocol_verified:c?.probe?.protocolVerified===true,tunnel_verified:c?.probe?.tunnelVerified===true},issues,candidates:candidates(c)}}
  async function aiHealth(){const badge=$('#ph25HfStatus'),out=$('#ph25HfAdvice');if(badge)badge.textContent='AI: checking…';try{const r=await fetch('/api/ai/health',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.error||`HTTP ${r.status}`);if(badge){badge.textContent=d.loaded?`Qwen: ready · ${d.model}`:`Rules fallback · ${d.model}`;badge.dataset.state=d.loaded?'ready':'rules'}if(out){out.style.display='block';out.textContent=d.loaded?'Qwen advisor is available. Model advice remains advisory; verification still requires Real Test.':'HF model/token is not loaded. Deterministic repair remains available and never marks a config verified.'}return d}catch(e){if(badge){badge.textContent='AI endpoint offline';badge.dataset.state='offline'}if(out){out.style.display='block';out.textContent=`AI health error: ${clean(e?.message||e)}`}return null}}
  async function aiThink(){const btn=$('#ph25ThinkBtn'),out=$('#ph25HfAdvice');$('#aiAnalyzeBtn')?.click();const cs=$$('.ai-cfg-check:checked').slice(0,25),all=state().configs||[],idx=cs.map(x=>num(x.dataset.idx)).filter(i=>all[i]),fallback=all.map((c,i)=>({c,i})).filter(x=>failed(x.c)||!verified(x.c)).slice(0,25).map(x=>x.i),sel=idx.length?idx:fallback;if(!sel.length)return toast('No unverified/failed configs are available for advisor review.','warn');const items=sel.map(i=>advisorItem(all[i],i));if(btn){btn.disabled=true;btn.textContent='Thinking…'}if(out){out.style.display='block';out.textContent=`Reviewing ${items.length} sanitized configs…`}try{const r=await fetch('/api/ai/advise',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.error||`HTTP ${r.status}`);const lines=[`Mode: ${d.mode}`,`Model: ${d.model||'rules'}`,`Reviewed: ${items.length}`];for(const x of(d.items||[]).slice(0,12))lines.push(`#${x.index}: ${x.decision} · ${(x.candidate_ids||[]).join(', ')||'manual review'} · ${x.confidence||0}%`);if(d.warning)lines.push(`Warning: ${clean(d.warning)}`);if(d.model_text)lines.push(`\nModel advisory:\n${String(d.model_text).slice(0,1800)}`);lines.push('\nAdvice does not change verification state. Use local safe fixes, then Real Verify.');if(out)out.textContent=lines.join('\n');toast(`Advisor reviewed ${items.length} configs.`,d.loaded?'ok':'warn')}catch(e){if(out)out.textContent=`Advisor error: ${clean(e?.message||e)}`;toast('AI advisor request failed.','err')}finally{if(btn){btn.disabled=false;btn.textContent='✦ Think with Qwen'}}}
  function ensureAI(){const tab=$('#tab-ai-healer');if(!tab||tab.dataset.phv26==='1')return;tab.dataset.phv26='1';$('#ph25HfHealthBtn')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();aiHealth()},true);$('#ph25ThinkBtn')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();aiThink()},true);aiHealth()}

  function group(s){const t=clean($('.settings-section-hdr',s)?.textContent||s.textContent).toLowerCase();if(t.includes('appearance'))return'appearance';if(t.includes('local bridge')||t.includes('real ping'))return'verification';if(t.includes('network')||t.includes('cors'))return'network';if(t.includes('performance'))return'performance';if(t.includes('scoring'))return'scoring';if(t.includes('auto fetch')||t.includes('general'))return'harvest';return'advanced'}
  function ensureSettings(){const tab=$('#tab-settings'),body=$('#settingsContent');if(!tab||!body||$('#phv26SettingsNav'))return;const nav=document.createElement('div');nav.id='phv26SettingsNav';nav.className='phv26-settings-nav';nav.innerHTML='<div><b>Settings</b><span>Recommended controls first; advanced fields stay available.</span></div><div class="phv26-setting-tabs"><button class="active" data-group="recommended">Recommended</button><button data-group="appearance">Appearance</button><button data-group="harvest">Harvest</button><button data-group="verification">Real Ping</button><button data-group="network">Network</button><button data-group="performance">Performance</button><button data-group="scoring">Scoring</button><button data-group="all">All</button></div>';body.insertAdjacentElement('afterbegin',nav);const st=document.createElement('div');st.id='phv26SettingsStatus';st.className='phv26-settings-status';nav.insertAdjacentElement('afterend',st);const sections=$$('.settings-section',body);sections.forEach(s=>s.dataset.phv26Group=group(s));const show=g=>{sections.forEach(s=>s.hidden=g!=='all'&&(g==='recommended'?!['appearance','harvest','verification'].includes(s.dataset.phv26Group):s.dataset.phv26Group!==g));$$('[data-group]',nav).forEach(b=>b.classList.toggle('active',b.dataset.group===g))};nav.addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(b)show(b.dataset.group)});show('recommended');refreshSettings()}
  function refreshSettings(){const r=$('#phv26SettingsStatus');if(!r)return;let w=$('#cfg-worker-url')?.value?.trim()||'default gateway';try{w=w||localStorage.getItem('cfg_worker_url')||'default gateway'}catch{}const strict=$('#cfg-strictRealPing')?.checked??true,thr=$('#cfg-scoreThresholdSettings')?.value??$('#cfg-scoreThreshold')?.value??0,b=bridge();setHtmlStable(r,`<div><span>Real Bridge</span><b class="${b?'ok':'warn'}">${b?'Configured':'Optional / missing'}</b></div><div><span>Worker</span><b>${clean(w)}</b></div><div><span>Strict Real Ping</span><b class="${strict?'ok':'warn'}">${strict?'Enabled':'Disabled'}</b></div><div><span>Export score floor</span><b>${clean(thr)}</b></div>`)}
  async function check(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});return{ok:r.ok,status:r.status}}catch(e){return{ok:false,error:clean(e?.message||e)}}finally{clearTimeout(t)}}
  function ensureInfra(){const tab=$('#tab-infrastructure');if(!tab||$('#phv26InfraStatus',tab))return;const box=document.createElement('div');box.id='phv26InfraStatus';box.className='phv26-infra-status';box.innerHTML='<div class="phv26-panel-head"><div><b>Runtime usage</b><span>This page configures the fetch gateway and optional local verifier. Worker reachability is not tunnel verification.</span></div><button class="phv26-btn" id="phv26CheckInfra">Check now</button></div><div class="phv26-infra-grid"><div><span>Worker</span><b id="phv26WorkerCheck">Not checked</b></div><div><span>Real Bridge</span><b id="phv26BridgeCheck">Not checked</b></div><div><span>AI API</span><b id="phv26AiCheck">Not checked</b></div></div>';tab.insertAdjacentElement('afterbegin',box);$('#phv26CheckInfra')?.addEventListener('click',checkInfra)}
  async function checkInfra(){const wr=($('#cfg-worker-url')?.value?.trim()||'').replace(/\/$/,'').replace(/\?url=$/,''),br=bridge(),w=$('#phv26WorkerCheck'),b=$('#phv26BridgeCheck'),a=$('#phv26AiCheck');if(w)w.textContent=wr?'Checking…':'Not configured';if(b)b.textContent=br?'Checking…':'Not configured';if(a)a.textContent='Checking…';if(wr){const r=await check(wr+'/health');if(w)w.textContent=r.ok?`Reachable · HTTP ${r.status}`:`Unavailable${r.error?' · '+r.error:''}`}if(br){const r=await check(br+'/health');if(b)b.textContent=r.ok?`Ready · HTTP ${r.status}`:`Unavailable${r.error?' · '+r.error:''}`}try{const r=await fetch('/api/ai/health',{cache:'no-store'}),d=await r.json();if(a)a.textContent=d.loaded?`Model ready · ${d.model}`:`Rules fallback · ${d.model||'no model'}`}catch(e){if(a)a.textContent=`Offline · ${clean(e?.message||e)}`}}
  function mark(){document.documentElement.dataset.phv26='1';const h=$('.ph-main-head')||$('.main-head')||$('.header');if(h&&!$('.phv26-build-badge',h)){const b=document.createElement('span');b.className='phv26-build-badge';b.textContent='GitHub main · V26 UI';h.appendChild(b)}}
  function boot(){mark();ensureConfigs();ensureSplit();ensureWG();ensureAI();ensureSettings();ensureInfra();refreshVerify();refreshSplit();refreshWG();refreshSettings();let ensureTimer=null;const ensure=()=>{if(ensureTimer)return;ensureTimer=setTimeout(()=>{ensureTimer=null;ensureConfigs();ensureSplit();ensureWG();ensureAI();ensureSettings();ensureInfra()},100)};const o=new MutationObserver(records=>{if(records.some(r=>r.addedNodes?.length||r.removedNodes?.length))ensure()});o.observe($('.ph-content')||$('.content')||document.body,{childList:true,subtree:true});const periodic=setInterval(()=>{if(document.visibilityState!=='visible')return;refreshVerify();refreshSplit();refreshWG();refreshSettings()},5000);window.addEventListener('pagehide',()=>{o.disconnect();clearInterval(periodic);if(ensureTimer)clearTimeout(ensureTimer)},{once:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120));else setTimeout(boot,120);
})();
